# Generated by Django 3.2.7 on 2021-12-03 00:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 12, 3, 1, 48, 3, 915122))),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du quiz')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='', max_length=2000, verbose_name='Explication de la réponse'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Proposition'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct_answer',
            field=models.BooleanField(default=False, verbose_name='réponse correcte'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoQuiz.question', verbose_name='Question concernée'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1000, verbose_name='Intitulé de la question'),
        ),
        migrations.CreateModel(
            name='SessionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 12, 3, 1, 48, 3, 916122))),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoQuiz.menuquiz', verbose_name='Quiz associé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur courant')),
            ],
        ),
    ]
