# Generated by Django 3.2.7 on 2021-12-03 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0002_auto_20211203_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Explication de la réponse'),
        ),
        migrations.AlterField(
            model_name='sessionquiz',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 3, 8, 8, 339471)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 3, 8, 8, 337472)),
        ),
    ]
