# Generated by Django 3.2.7 on 2021-11-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0002_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='', max_length=2000, verbose_name='Explication de la réponse'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Proposition'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct_answer',
            field=models.BooleanField(default=False, verbose_name='réponse correcte'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoQuiz.question', verbose_name='Question concernée'),
        ),
    ]
