# Generated by Django 3.2.7 on 2021-12-03 01:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0002_auto_20211203_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquiz',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 2, 15, 32, 195222)),
        ),
        migrations.AlterField(
            model_name='sessionquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoQuiz.user', verbose_name='Utilisateur courant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 2, 15, 32, 194222)),
        ),
    ]
