# Generated by Django 3.2.7 on 2021-12-03 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0003_auto_20211203_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquiz',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 2, 17, 59, 738695)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 2, 17, 59, 736696)),
        ),
    ]
