# Generated by Django 3.2.7 on 2021-12-01 01:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0003_auto_20211125_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 12, 1, 2, 54, 35, 38312))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
