# Generated by Django 3.2.7 on 2021-12-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0003_auto_20211203_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquiz',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
