# Generated by Django 3.2.7 on 2021-12-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0005_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='associated_quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restoQuiz.menuquiz', verbose_name='De quel quiz fait parti cette question ?'),
            preserve_default=False,
        ),
    ]
