# Generated by Django 3.2.7 on 2021-12-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0006_question_associated_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquiz',
            name='current_number_good_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionquiz',
            name='current_question_index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
