# Generated by Django 3.2.7 on 2021-12-09 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0007_auto_20211203_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultScoreFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('nb_question', models.IntegerField(blank=True, default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoQuiz.menuquiz', verbose_name='Quiz associé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
