# Generated by Django 3.2.7 on 2021-12-15 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0009_resultscorefinal_is_final_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 13, 6, 3, 236529)),
        ),
    ]
