# Generated by Django 3.2.7 on 2021-12-01 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0009_auto_20211201_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 3, 32, 21, 375369)),
        ),
    ]
