# Generated by Django 3.2.7 on 2021-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0010_alter_user_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
