# Generated by Django 3.2.7 on 2021-12-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0011_alter_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultscorefinal',
            name='name_leaderboard',
            field=models.CharField(default='Non renseigné', max_length=200, verbose_name='Pseudo'),
        ),
    ]
