# Generated by Django 3.2.7 on 2021-12-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoQuiz', '0012_resultscorefinal_name_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscorefinal',
            name='name_leaderboard',
            field=models.CharField(default='Non renseigné', max_length=200, null=True, verbose_name='Pseudo'),
        ),
    ]
